### ISSUE TITLE
Create ObjectPool for cars

### ISSUE THREAD

**Issue by SethMC26** [gabyzola/Zola_Ouellette_Holtzman_3210_Final-#13]

**Comment by SethMC26** [comment]
Task blocked by #16

**Comment by SethMC26** [comment]
@SOuellette22 looks pretty good check it out when you have time - one thing I dont like is how the lane needs to know about the scene it kinda muddies everything up. I did this just get the death animation for the camera working again but we should probably look at a more "clean" solution.

**Comment by SOuellette22** [comment]
@SethMC26 Couldn't you have the scene as an input into the update function so that the lane does not need to be saved it inside each lane?

**Comment by SethMC26** [comment]
@SOuellette22 I updated in the most recent commit doing something similar to this, passing a boolean along that bubbles up if true.
